DROP SCHEMA IF EXISTS BABYPLUS;
CREATE SCHEMA IF NOT EXISTS BABYPLUS;

CREATE TABLE IF NOT EXISTS BABYPLUS.USUARIO
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
        USUARIO VARCHAR(50) NOT NULL,
        PASSWORD VARCHAR(50) NOT NULL,
        FECHA_ALTA DATE NOT NULL,
        ACTIVO TINYINT(1) NOT NULL DEFAULT 0
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS BABYPLUS.ROL
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
        DESCRIPCION VARCHAR(50) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS BABYPLUS.USUARIO_ROL
(
	USUARIO INT NOT NULL,
        ROL INT NOT NULL,
        PRIMARY KEY (USUARIO, ROL),
        FOREIGN KEY (USUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY (ROL) REFERENCES ROL(ID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS BABYPLUS.CLIENTE
(
	USUARIO INT NOT NULL,
        NOMBRE VARCHAR(50) NOT NULL,
        APELLIDOS VARCHAR(100) NOT NULL,
        FECHA_NACIMIENTO DATE NOT NULL,
        DOMICILIO VARCHAR(200) NOT NULL,
        LOCALIDAD VARCHAR(100) NOT NULL,
        CP INT(5) NOT NULL,
        PRIMARY KEY (USUARIO),
        FOREIGN KEY (USUARIO) REFERENCES USUARIO(ID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS BABYPLUS.PACIENTE
(
        ID INT AUTO_INCREMENT PRIMARY KEY,
	CLIENTE INT NOT NULL,
        NOMBRE VARCHAR(50) NOT NULL,
        FECHA_NACIMIENTO DATE NOT NULL,
        OBSERVACIONES VARCHAR(300),
        FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(USUARIO)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS BABYPLUS.PROVEEDOR
(
	USUARIO INT NOT NULL,
        RAZON_SOCIAL VARCHAR(50) NOT NULL,
        CIF VARCHAR(9) NOT NULL,
        DIRECCION VARCHAR(200) NOT NULL,
        LOCALIDAD VARCHAR(100) NOT NULL,
        CP INT(5) NOT NULL,
        LOGO LONGBLOB NOT NULL,
        RESPONSABLE VARCHAR(100),
        PRIMARY KEY (USUARIO),
        FOREIGN KEY (USUARIO) REFERENCES USUARIO(ID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS BABYPLUS.SERVICIO
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
        DESCRIPCION VARCHAR(150) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS BABYPLUS.PROVEEDOR_SERVICIO
(
	PROVEEDOR INT NOT NULL,
        SERVICIO INT NOT NULL,
        PRECIO INT NOT NULL,
        PRIMARY KEY (PROVEEDOR, SERVICIO),
        FOREIGN KEY (PROVEEDOR) REFERENCES PROVEEDOR(USUARIO),
        FOREIGN KEY (SERVICIO) REFERENCES SERVICIO(ID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;